export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'blackjack',
        'roulette',
        'slots',
        'baccarat',
        'wallet',
        'auth',
        'rng',
        'history',
        'stats',
        'leaderboard',
        'lottery',
        'bingo',
        'plinko',
        'poker',
        'theme',
        'db',
        'session',
        'lobby',
        'ci',
        'build-guide',
        'deps',
        'deps-dev',
        'release',
        'repo',
        'adr',
        'routing',
        'ui',
        'shell',
        'coin-flip',
        'games',
        'admin',
        'tracking',
        'baccarat',
        'craps',
      ],
    ],
    'subject-case': [0],
    'body-max-line-length': [0],
    'footer-max-line-length': [0],
  },
};
