export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'blackjack',
        'roulette',
        'slots',
        'baccarat',
        'wallet',
        'auth',
        'rng',
        'history',
        'stats',
        'leaderboard',
        'theme',
        'db',
        'session',
        'lobby',
        'ci',
        'build-guide',
        'deps',
        'deps-dev',
        'release',
        'repo',
        'adr',
        'routing',
      ],
    ],
    'subject-case': [0],
    'body-max-line-length': [0],
    'footer-max-line-length': [0],
  },
};
